#!/bin/bash

FW_NAME=$1
shift

ELF_PATH=build-bin/sw/device/examples/${FW_NAME}/${FW_NAME}_sim_verilator.elf

build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf --meminit=flash,$ELF_PATH $*
