// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [0:0][31:0] ADDR_SPACE_RAM_MAIN  = {
    32'h 10000000
  };
  localparam logic [0:0][31:0] ADDR_SPACE_DEBUG_MEM = {
    32'h 1a110000
  };
  localparam logic [0:0][31:0] ADDR_SPACE_GPIO      = {
    32'h 40000000
  };

  localparam logic [0:0][31:0] ADDR_MASK_RAM_MAIN  = {
    32'h 0000ffff
  };
  localparam logic [0:0][31:0] ADDR_MASK_DEBUG_MEM = {
    32'h 0000ffff
  };
  localparam logic [0:0][31:0] ADDR_MASK_GPIO      = {
    32'h 00000fff
  };

  localparam int N_HOST   = 3;
  localparam int N_DEVICE = 3;

  typedef enum int {
    TlRamMain = 0,
    TlDebugMem = 1,
    TlGpio = 2
  } tl_device_e;

  typedef enum int {
    TlCorei = 0,
    TlCored = 1,
    TlDmSba = 2
  } tl_host_e;

endpackage
