// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ise_reg_pkg;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] d;
  } ise_hw2reg_status_reg_t;


  ///////////////////////////////////////
  // Register to internal design logic //
  ///////////////////////////////////////

  ///////////////////////////////////////
  // Internal design logic to register //
  ///////////////////////////////////////
  typedef struct packed {
    ise_hw2reg_status_reg_t status; // [31:32]
  } ise_hw2reg_t;

  // Register Address
  parameter logic [3:0] ISE_DATA0_OFFSET = 4'h 0;
  parameter logic [3:0] ISE_DATA1_OFFSET = 4'h 4;
  parameter logic [3:0] ISE_STATUS_OFFSET = 4'h 8;


  // Register Index
  typedef enum int {
    ISE_DATA0,
    ISE_DATA1,
    ISE_STATUS
  } ise_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ISE_PERMIT [3] = '{
    4'b 1111, // index[0] ISE_DATA0
    4'b 1111, // index[1] ISE_DATA1
    4'b 1111  // index[2] ISE_STATUS
  };
endpackage

